brew 'diff-so-fancy'

# utilities
brew 'appledoc'
brew 'dos2unix'
brew 'gpg'
brew 'p7zip'
brew 'pandoc'
brew 'pstree'
brew 'ssh-copy-id'
brew 'tree'
brew 'unrar'
brew 'valgrind'
brew 'wget'

# build tools
brew 'cmake'
brew 'gradle'

# package manager
brew 'chruby'
brew 'ruby-install'
brew 'haskell-stack'
brew 'nvm'
brew 'pyenv'
brew 'pyenv-virtualenv'

############
# Caskroom #
############
tap 'Caskroom/cask'
cask 'cocoapods-app'
cask 'docker'
cask 'macdown'
cask 'squirrel'
cask 'sublime-text'
cask 'texstudio'
cask 'vagrant'
cask 'virtualbox'
